version: '3.8'
services:
  postgres-db:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - postgres-pgadmin-network
      - backend-postgres-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "16543:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres-db
    networks:
      - postgres-pgadmin-network

  backend:
    build:
      context: /backend
      no_cache: true
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
    networks:
      - backend-postgres-network
      - backend-frontend-network

  web-frontend:
    build:
      context: /frontend
      no_cache: true
    environment:
      - NODE_ENV=${ENV}
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - backend-frontend-network

networks:
  postgres-pgadmin-network:
    driver: bridge
  backend-postgres-network:
    driver: bridge
  backend-frontend-network:
    driver: bridge
